name: Lint and Test Go Code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run linters
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.1.6

      - name: Run tests
        run: go test -v -race ./...
